import type { Word } from './types'

// 内置词库 - 约200个高频英语单词（CET-4级别），按难度分级
export const wordDatabase: Word[] = [
  // === 难度 1：基础词汇 ===
  { id: 'w001', word: 'abandon', phonetic: '/əˈbændən/', partOfSpeech: 'v.', meaning: '放弃；抛弃', example: 'He abandoned his plan to travel abroad.', exampleTranslation: '他放弃了出国旅行的计划。', difficulty: 1 },
  { id: 'w002', word: 'ability', phonetic: '/əˈbɪləti/', partOfSpeech: 'n.', meaning: '能力；才能', example: 'She has the ability to solve complex problems.', exampleTranslation: '她有能力解决复杂问题。', difficulty: 1 },
  { id: 'w003', word: 'abroad', phonetic: '/əˈbrɔːd/', partOfSpeech: 'adv.', meaning: '在国外；到国外', example: 'He went abroad to study last year.', exampleTranslation: '他去年去国外留学了。', difficulty: 1 },
  { id: 'w004', word: 'absence', phonetic: '/ˈæbsəns/', partOfSpeech: 'n.', meaning: '缺席；不在', example: 'His absence was noticed by everyone.', exampleTranslation: '他的缺席被每个人注意到了。', difficulty: 1 },
  { id: 'w005', word: 'absorb', phonetic: '/əbˈzɔːrb/', partOfSpeech: 'v.', meaning: '吸收；吸引', example: 'Plants absorb water through their roots.', exampleTranslation: '植物通过根部吸收水分。', difficulty: 1 },
  { id: 'w006', word: 'achieve', phonetic: '/əˈtʃiːv/', partOfSpeech: 'v.', meaning: '实现；达到', example: 'She achieved her goal of becoming a doctor.', exampleTranslation: '她实现了成为医生的目标。', difficulty: 1 },
  { id: 'w007', word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', partOfSpeech: 'v.', meaning: '承认；确认', example: 'He acknowledged his mistake immediately.', exampleTranslation: '他立即承认了自己的错误。', difficulty: 1 },
  { id: 'w008', word: 'acquire', phonetic: '/əˈkwaɪər/', partOfSpeech: 'v.', meaning: '获得；习得', example: 'She acquired a new skill through practice.', exampleTranslation: '她通过练习习得了一项新技能。', difficulty: 1 },
  { id: 'w009', word: 'adapt', phonetic: '/əˈdæpt/', partOfSpeech: 'v.', meaning: '适应；改编', example: 'You need to adapt to the new environment.', exampleTranslation: '你需要适应新环境。', difficulty: 1 },
  { id: 'w010', word: 'adequate', phonetic: '/ˈædɪkwət/', partOfSpeech: 'adj.', meaning: '足够的；适当的', example: 'The food supply is adequate for the team.', exampleTranslation: '食物供应对团队来说是足够的。', difficulty: 1 },
  { id: 'w011', word: 'adjust', phonetic: '/əˈdʒʌst/', partOfSpeech: 'v.', meaning: '调整；适应', example: 'Please adjust the volume of the TV.', exampleTranslation: '请调整电视的音量。', difficulty: 1 },
  { id: 'w012', word: 'admire', phonetic: '/ədˈmaɪər/', partOfSpeech: 'v.', meaning: '钦佩；欣赏', example: 'I admire her courage and determination.', exampleTranslation: '我钦佩她的勇气和决心。', difficulty: 1 },
  { id: 'w013', word: 'admit', phonetic: '/ədˈmɪt/', partOfSpeech: 'v.', meaning: '承认；准许进入', example: 'He admitted that he was wrong.', exampleTranslation: '他承认自己错了。', difficulty: 1 },
  { id: 'w014', word: 'adopt', phonetic: '/əˈdɒpt/', partOfSpeech: 'v.', meaning: '采纳；收养', example: 'They decided to adopt a child.', exampleTranslation: '他们决定收养一个孩子。', difficulty: 1 },
  { id: 'w015', word: 'advance', phonetic: '/ədˈvɑːns/', partOfSpeech: 'v./n.', meaning: '前进；进步', example: 'Technology continues to advance rapidly.', exampleTranslation: '技术继续快速发展。', difficulty: 1 },
  { id: 'w016', word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', partOfSpeech: 'n.', meaning: '优势；有利条件', example: 'His experience gives him an advantage.', exampleTranslation: '他的经验给了他一个优势。', difficulty: 1 },
  { id: 'w017', word: 'affect', phonetic: '/əˈfekt/', partOfSpeech: 'v.', meaning: '影响；感动', example: 'The weather can affect your mood.', exampleTranslation: '天气会影响你的心情。', difficulty: 1 },
  { id: 'w018', word: 'afford', phonetic: '/əˈfɔːrd/', partOfSpeech: 'v.', meaning: '买得起；承担得起', example: 'I cannot afford a new car right now.', exampleTranslation: '我现在买不起新车。', difficulty: 1 },
  { id: 'w019', word: 'aggressive', phonetic: '/əˈɡresɪv/', partOfSpeech: 'adj.', meaning: '侵略性的；好斗的', example: 'The dog became aggressive towards strangers.', exampleTranslation: '那条狗对陌生人变得有攻击性。', difficulty: 1 },
  { id: 'w020', word: 'agree', phonetic: '/əˈɡriː/', partOfSpeech: 'v.', meaning: '同意；一致', example: 'I agree with your opinion on this matter.', exampleTranslation: '在这件事上我同意你的看法。', difficulty: 1 },
  { id: 'w021', word: 'ahead', phonetic: '/əˈhed/', partOfSpeech: 'adv.', meaning: '在前面；提前', example: 'Go ahead, I will catch up later.', exampleTranslation: '你先走，我稍后赶上。', difficulty: 1 },
  { id: 'w022', word: 'alarm', phonetic: '/əˈlɑːrm/', partOfSpeech: 'n./v.', meaning: '警报；使惊恐', example: 'The fire alarm went off at midnight.', exampleTranslation: '火灾警报在午夜响起。', difficulty: 1 },
  { id: 'w023', word: 'allow', phonetic: '/əˈlaʊ/', partOfSpeech: 'v.', meaning: '允许；准许', example: 'Smoking is not allowed in this building.', exampleTranslation: '这栋楼里不允许吸烟。', difficulty: 1 },
  { id: 'w024', word: 'amazing', phonetic: '/əˈmeɪzɪŋ/', partOfSpeech: 'adj.', meaning: '惊人的；了不起的', example: 'The view from the mountain was amazing.', exampleTranslation: '从山上看到的景色令人惊叹。', difficulty: 1 },
  { id: 'w025', word: 'ambition', phonetic: '/æmˈbɪʃən/', partOfSpeech: 'n.', meaning: '雄心；抱负', example: 'His ambition is to become a successful writer.', exampleTranslation: '他的抱负是成为一名成功的作家。', difficulty: 1 },
  { id: 'w026', word: 'amount', phonetic: '/əˈmaʊnt/', partOfSpeech: 'n.', meaning: '数量；总额', example: 'A large amount of money was donated.', exampleTranslation: '一大笔钱被捐赠了。', difficulty: 1 },
  { id: 'w027', word: 'analyze', phonetic: '/ˈænəlaɪz/', partOfSpeech: 'v.', meaning: '分析；解析', example: 'We need to analyze the data carefully.', exampleTranslation: '我们需要仔细分析数据。', difficulty: 1 },
  { id: 'w028', word: 'ancient', phonetic: '/ˈeɪnʃənt/', partOfSpeech: 'adj.', meaning: '古老的；古代的', example: 'They visited an ancient temple in China.', exampleTranslation: '他们参观了中国的一座古庙。', difficulty: 1 },
  { id: 'w029', word: 'announce', phonetic: '/əˈnaʊns/', partOfSpeech: 'v.', meaning: '宣布；宣告', example: 'The president announced the new policy.', exampleTranslation: '总统宣布了新政策。', difficulty: 1 },
  { id: 'w030', word: 'annual', phonetic: '/ˈænjuəl/', partOfSpeech: 'adj.', meaning: '年度的；每年的', example: 'The annual meeting will be held in March.', exampleTranslation: '年度会议将在三月举行。', difficulty: 1 },
  { id: 'w031', word: 'anxious', phonetic: '/ˈæŋkʃəs/', partOfSpeech: 'adj.', meaning: '焦虑的；渴望的', example: 'She was anxious about the exam results.', exampleTranslation: '她对考试结果感到焦虑。', difficulty: 1 },
  { id: 'w032', word: 'apparent', phonetic: '/əˈpærənt/', partOfSpeech: 'adj.', meaning: '明显的；表面上的', example: 'It was apparent that he was lying.', exampleTranslation: '很明显他在撒谎。', difficulty: 1 },
  { id: 'w033', word: 'appeal', phonetic: '/əˈpiːl/', partOfSpeech: 'v./n.', meaning: '呼吁；吸引力', example: 'The idea appeals to young people.', exampleTranslation: '这个想法对年轻人有吸引力。', difficulty: 1 },
  { id: 'w034', word: 'apply', phonetic: '/əˈplaɪ/', partOfSpeech: 'v.', meaning: '申请；应用', example: 'I want to apply for this job position.', exampleTranslation: '我想申请这个职位。', difficulty: 1 },
  { id: 'w035', word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', partOfSpeech: 'v.', meaning: '感激；欣赏', example: 'I appreciate your help very much.', exampleTranslation: '我非常感谢你的帮助。', difficulty: 1 },
  { id: 'w036', word: 'approach', phonetic: '/əˈprəʊtʃ/', partOfSpeech: 'v./n.', meaning: '接近；方法', example: 'We need a different approach to this problem.', exampleTranslation: '我们需要用不同的方法来解决这个问题。', difficulty: 1 },
  { id: 'w037', word: 'appropriate', phonetic: '/əˈprəʊpriət/', partOfSpeech: 'adj.', meaning: '适当的；合适的', example: 'Casual clothes are not appropriate for this event.', exampleTranslation: '休闲服装不适合这个场合。', difficulty: 1 },
  { id: 'w038', word: 'approve', phonetic: '/əˈpruːv/', partOfSpeech: 'v.', meaning: '批准；赞同', example: 'The committee approved the new proposal.', exampleTranslation: '委员会批准了新提案。', difficulty: 1 },
  { id: 'w039', word: 'arise', phonetic: '/əˈraɪz/', partOfSpeech: 'v.', meaning: '出现；产生', example: 'New problems arise every day.', exampleTranslation: '每天都会出现新问题。', difficulty: 1 },
  { id: 'w040', word: 'arrange', phonetic: '/əˈreɪndʒ/', partOfSpeech: 'v.', meaning: '安排；整理', example: 'She arranged the flowers in a vase.', exampleTranslation: '她把花插在花瓶里。', difficulty: 1 },

  // === 难度 2：进阶词汇 ===
  { id: 'w041', word: 'assessment', phonetic: '/əˈsesmənt/', partOfSpeech: 'n.', meaning: '评估；评价', example: 'The teacher made an assessment of each student.', exampleTranslation: '老师对每个学生进行了评估。', difficulty: 2 },
  { id: 'w042', word: 'assign', phonetic: '/əˈsaɪn/', partOfSpeech: 'v.', meaning: '分配；指派', example: 'The manager assigned tasks to each team member.', exampleTranslation: '经理给每个团队成员分配了任务。', difficulty: 2 },
  { id: 'w043', word: 'associate', phonetic: '/əˈsəʊʃieɪt/', partOfSpeech: 'v.', meaning: '联想；联系', example: 'People associate spring with new beginnings.', exampleTranslation: '人们把春天与新的开始联系在一起。', difficulty: 2 },
  { id: 'w044', word: 'assume', phonetic: '/əˈsjuːm/', partOfSpeech: 'v.', meaning: '假定；承担', example: 'I assume he will be late again.', exampleTranslation: '我猜他又要迟到了。', difficulty: 2 },
  { id: 'w045', word: 'atmosphere', phonetic: '/ˈætməsfɪər/', partOfSpeech: 'n.', meaning: '气氛；大气层', example: 'The restaurant had a romantic atmosphere.', exampleTranslation: '这家餐厅有浪漫的气氛。', difficulty: 2 },
  { id: 'w046', word: 'attach', phonetic: '/əˈtætʃ/', partOfSpeech: 'v.', meaning: '附上；连接', example: 'Please attach your resume to the email.', exampleTranslation: '请将简历附在邮件中。', difficulty: 2 },
  { id: 'w047', word: 'attempt', phonetic: '/əˈtempt/', partOfSpeech: 'v./n.', meaning: '尝试；企图', example: 'He made an attempt to climb the mountain.', exampleTranslation: '他尝试攀登那座山。', difficulty: 2 },
  { id: 'w048', word: 'attain', phonetic: '/əˈteɪn/', partOfSpeech: 'v.', meaning: '达到；获得', example: 'She attained the highest score in the class.', exampleTranslation: '她取得了班级最高分。', difficulty: 2 },
  { id: 'w049', word: 'attitude', phonetic: '/ˈætɪtjuːd/', partOfSpeech: 'n.', meaning: '态度；看法', example: 'A positive attitude leads to success.', exampleTranslation: '积极的态度导向成功。', difficulty: 2 },
  { id: 'w050', word: 'attribute', phonetic: '/əˈtrɪbjuːt/', partOfSpeech: 'v./n.', meaning: '归因于；属性', example: 'They attribute their success to hard work.', exampleTranslation: '他们把成功归因于努力工作。', difficulty: 2 },
  { id: 'w051', word: 'authentic', phonetic: '/ɔːˈθentɪk/', partOfSpeech: 'adj.', meaning: '真正的；可信的', example: 'The painting is an authentic masterpiece.', exampleTranslation: '这幅画是一件真正的杰作。', difficulty: 2 },
  { id: 'w052', word: 'authority', phonetic: '/ɔːˈθɒrəti/', partOfSpeech: 'n.', meaning: '权威；权力', example: 'He is an authority on Chinese history.', exampleTranslation: '他是中国历史方面的权威。', difficulty: 2 },
  { id: 'w053', word: 'available', phonetic: '/əˈveɪləbl/', partOfSpeech: 'adj.', meaning: '可用的；有空的', example: 'Are you available for a meeting tomorrow?', exampleTranslation: '你明天有空开会吗？', difficulty: 2 },
  { id: 'w054', word: 'bargain', phonetic: '/ˈbɑːɡɪn/', partOfSpeech: 'n./v.', meaning: '便宜货；讨价还价', example: 'This coat was a real bargain at half price.', exampleTranslation: '这件外套半价真是便宜。', difficulty: 2 },
  { id: 'w055', word: 'barrier', phonetic: '/ˈbæriər/', partOfSpeech: 'n.', meaning: '障碍；屏障', example: 'Language is a barrier to communication.', exampleTranslation: '语言是沟通的障碍。', difficulty: 2 },
  { id: 'w056', word: 'beneficial', phonetic: '/ˌbenɪˈfɪʃəl/', partOfSpeech: 'adj.', meaning: '有益的；有利的', example: 'Exercise is beneficial to your health.', exampleTranslation: '运动对你的健康有益。', difficulty: 2 },
  { id: 'w057', word: 'beyond', phonetic: '/bɪˈjɒnd/', partOfSpeech: 'prep.', meaning: '超出；在…之外', example: 'The situation is beyond my control.', exampleTranslation: '情况超出了我的控制。', difficulty: 2 },
  { id: 'w058', word: 'bias', phonetic: '/ˈbaɪəs/', partOfSpeech: 'n.', meaning: '偏见；偏差', example: 'The report was criticized for its bias.', exampleTranslation: '这份报告因其偏见而受到批评。', difficulty: 2 },
  { id: 'w059', word: 'bond', phonetic: '/bɒnd/', partOfSpeech: 'n.', meaning: '纽带；债券', example: 'The bond between mother and child is strong.', exampleTranslation: '母亲和孩子之间的纽带很强。', difficulty: 2 },
  { id: 'w060', word: 'boost', phonetic: '/buːst/', partOfSpeech: 'v./n.', meaning: '促进；提升', example: 'This news will boost our confidence.', exampleTranslation: '这个消息会增强我们的信心。', difficulty: 2 },
  { id: 'w061', word: 'boundary', phonetic: '/ˈbaʊndəri/', partOfSpeech: 'n.', meaning: '边界；界限', example: 'The river forms the boundary between the two countries.', exampleTranslation: '这条河构成了两国之间的边界。', difficulty: 2 },
  { id: 'w062', word: 'budget', phonetic: '/ˈbʌdʒɪt/', partOfSpeech: 'n.', meaning: '预算；开支', example: 'We need to stay within our budget.', exampleTranslation: '我们需要控制在预算之内。', difficulty: 2 },
  { id: 'w063', word: 'burden', phonetic: '/ˈbɜːrdn/', partOfSpeech: 'n.', meaning: '负担；重担', example: 'The tax burden on families has increased.', exampleTranslation: '家庭的税收负担增加了。', difficulty: 2 },
  { id: 'w064', word: 'campaign', phonetic: '/kæmˈpeɪn/', partOfSpeech: 'n.', meaning: '运动；战役', example: 'The company launched a new advertising campaign.', exampleTranslation: '公司发起了新的广告活动。', difficulty: 2 },
  { id: 'w065', word: 'candidate', phonetic: '/ˈkændɪdət/', partOfSpeech: 'n.', meaning: '候选人；应聘者', example: 'She is the best candidate for this position.', exampleTranslation: '她是这个职位的最佳候选人。', difficulty: 2 },
  { id: 'w066', word: 'capable', phonetic: '/ˈkeɪpəbl/', partOfSpeech: 'adj.', meaning: '有能力的；能干的', example: 'He is capable of handling this project.', exampleTranslation: '他有能力处理这个项目。', difficulty: 2 },
  { id: 'w067', word: 'capture', phonetic: '/ˈkæptʃər/', partOfSpeech: 'v.', meaning: '捕获；占领', example: 'The photographer captured a beautiful sunset.', exampleTranslation: '摄影师拍下了美丽的日落。', difficulty: 2 },
  { id: 'w068', word: 'career', phonetic: '/kəˈrɪər/', partOfSpeech: 'n.', meaning: '职业；事业', example: 'She had a successful career in medicine.', exampleTranslation: '她在医学界有一个成功的职业生涯。', difficulty: 2 },
  { id: 'w069', word: 'category', phonetic: '/ˈkætəɡəri/', partOfSpeech: 'n.', meaning: '类别；范畴', example: 'The products fall into three categories.', exampleTranslation: '这些产品分为三类。', difficulty: 2 },
  { id: 'w070', word: 'cease', phonetic: '/siːs/', partOfSpeech: 'v.', meaning: '停止；终止', example: 'The factory ceased production last month.', exampleTranslation: '工厂上个月停止了生产。', difficulty: 2 },
  { id: 'w071', word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', partOfSpeech: 'n./v.', meaning: '挑战；质疑', example: 'Learning a new language is a big challenge.', exampleTranslation: '学习一门新语言是一个很大的挑战。', difficulty: 2 },
  { id: 'w072', word: 'circumstance', phonetic: '/ˈsɜːrkəmstəns/', partOfSpeech: 'n.', meaning: '情况；环境', example: 'Under no circumstance should you give up.', exampleTranslation: '在任何情况下你都不应该放弃。', difficulty: 2 },
  { id: 'w073', word: 'civilization', phonetic: '/ˌsɪvəlaɪˈzeɪʃən/', partOfSpeech: 'n.', meaning: '文明；文化', example: 'Ancient Chinese civilization influenced the world.', exampleTranslation: '中国古代文明影响了世界。', difficulty: 2 },
  { id: 'w074', word: 'claim', phonetic: '/kleɪm/', partOfSpeech: 'v./n.', meaning: '声称；要求', example: 'He claims to be an expert in this field.', exampleTranslation: '他声称自己是这个领域的专家。', difficulty: 2 },
  { id: 'w075', word: 'classify', phonetic: '/ˈklæsɪfaɪ/', partOfSpeech: 'v.', meaning: '分类；归类', example: 'We classify animals into different groups.', exampleTranslation: '我们把动物分成不同的组。', difficulty: 2 },
  { id: 'w076', word: 'collapse', phonetic: '/kəˈlæps/', partOfSpeech: 'v./n.', meaning: '倒塌；崩溃', example: 'The building collapsed during the earthquake.', exampleTranslation: '那栋建筑在地震中倒塌了。', difficulty: 2 },
  { id: 'w077', word: 'colleague', phonetic: '/ˈkɒliːɡ/', partOfSpeech: 'n.', meaning: '同事；同行', example: 'My colleague helped me with the project.', exampleTranslation: '我的同事帮我完成了项目。', difficulty: 2 },
  { id: 'w078', word: 'commence', phonetic: '/kəˈmens/', partOfSpeech: 'v.', meaning: '开始；着手', example: 'The ceremony will commence at ten o\'clock.', exampleTranslation: '仪式将于十点开始。', difficulty: 2 },
  { id: 'w079', word: 'commit', phonetic: '/kəˈmɪt/', partOfSpeech: 'v.', meaning: '承诺；犯（罪）', example: 'He committed himself to finishing the work.', exampleTranslation: '他承诺完成这项工作。', difficulty: 2 },
  { id: 'w080', word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', partOfSpeech: 'v.', meaning: '交流；传达', example: 'It is important to communicate clearly.', exampleTranslation: '清楚地交流很重要。', difficulty: 2 },

  // === 难度 3：中级词汇 ===
  { id: 'w081', word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', partOfSpeech: 'v.', meaning: '补偿；赔偿', example: 'The company will compensate you for the loss.', exampleTranslation: '公司将赔偿你的损失。', difficulty: 3 },
  { id: 'w082', word: 'competent', phonetic: '/ˈkɒmpɪtənt/', partOfSpeech: 'adj.', meaning: '有能力的；胜任的', example: 'She is a competent and reliable worker.', exampleTranslation: '她是一个称职可靠的工作者。', difficulty: 3 },
  { id: 'w083', word: 'complicated', phonetic: '/ˈkɒmplɪkeɪtɪd/', partOfSpeech: 'adj.', meaning: '复杂的；难懂的', example: 'The instructions were too complicated to follow.', exampleTranslation: '说明书太复杂了，难以理解。', difficulty: 3 },
  { id: 'w084', word: 'component', phonetic: '/kəmˈpəʊnənt/', partOfSpeech: 'n.', meaning: '成分；组件', example: 'Each component of the machine must be tested.', exampleTranslation: '机器的每个组件都必须经过测试。', difficulty: 3 },
  { id: 'w085', word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', partOfSpeech: 'adj.', meaning: '全面的；综合的', example: 'The report provides a comprehensive overview.', exampleTranslation: '这份报告提供了全面的概述。', difficulty: 3 },
  { id: 'w086', word: 'concentrate', phonetic: '/ˈkɒnsntreɪt/', partOfSpeech: 'v.', meaning: '集中；专注', example: 'I need to concentrate on my studies.', exampleTranslation: '我需要专注于学习。', difficulty: 3 },
  { id: 'w087', word: 'concept', phonetic: '/ˈkɒnsept/', partOfSpeech: 'n.', meaning: '概念；观念', example: 'The concept of freedom means different things.', exampleTranslation: '自由的概念意味着不同的东西。', difficulty: 3 },
  { id: 'w088', word: 'conclude', phonetic: '/kənˈkluːd/', partOfSpeech: 'v.', meaning: '得出结论；结束', example: 'We concluded that more research was needed.', exampleTranslation: '我们得出结论，需要更多研究。', difficulty: 3 },
  { id: 'w089', word: 'concrete', phonetic: '/ˈkɒŋkriːt/', partOfSpeech: 'adj./n.', meaning: '具体的；混凝土', example: 'We need concrete evidence to prove it.', exampleTranslation: '我们需要具体的证据来证明。', difficulty: 3 },
  { id: 'w090', word: 'conduct', phonetic: '/kənˈdʌkt/', partOfSpeech: 'v./n.', meaning: '进行；行为', example: 'The scientist conducted an experiment.', exampleTranslation: '科学家进行了一项实验。', difficulty: 3 },
  { id: 'w091', word: 'confine', phonetic: '/kənˈfaɪn/', partOfSpeech: 'v.', meaning: '限制；局限', example: 'He was confined to bed for a week.', exampleTranslation: '他卧床休息了一周。', difficulty: 3 },
  { id: 'w092', word: 'confirm', phonetic: '/kənˈfɜːrm/', partOfSpeech: 'v.', meaning: '确认；证实', example: 'Please confirm your attendance by email.', exampleTranslation: '请通过邮件确认你的出席。', difficulty: 3 },
  { id: 'w093', word: 'conflict', phonetic: '/ˈkɒnflɪkt/', partOfSpeech: 'n./v.', meaning: '冲突；矛盾', example: 'The two countries resolved their conflict.', exampleTranslation: '两国解决了他们的冲突。', difficulty: 3 },
  { id: 'w094', word: 'confront', phonetic: '/kənˈfrʌnt/', partOfSpeech: 'v.', meaning: '面对；对抗', example: 'You must confront your fears directly.', exampleTranslation: '你必须直接面对你的恐惧。', difficulty: 3 },
  { id: 'w095', word: 'conscious', phonetic: '/ˈkɒnʃəs/', partOfSpeech: 'adj.', meaning: '有意识的；意识到的', example: 'She was conscious of being watched.', exampleTranslation: '她意识到有人在看她。', difficulty: 3 },
  { id: 'w096', word: 'consensus', phonetic: '/kənˈsensəs/', partOfSpeech: 'n.', meaning: '共识；一致意见', example: 'The team reached a consensus on the plan.', exampleTranslation: '团队在计划上达成了共识。', difficulty: 3 },
  { id: 'w097', word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', partOfSpeech: 'n.', meaning: '后果；结果', example: 'He suffered the consequences of his actions.', exampleTranslation: '他承受了自己行为的后果。', difficulty: 3 },
  { id: 'w098', word: 'considerable', phonetic: '/kənˈsɪdərəbl/', partOfSpeech: 'adj.', meaning: '相当大的；重要的', example: 'She earned a considerable amount of money.', exampleTranslation: '她赚了相当多的钱。', difficulty: 3 },
  { id: 'w099', word: 'consistent', phonetic: '/kənˈsɪstənt/', partOfSpeech: 'adj.', meaning: '一致的；始终如一的', example: 'His results were consistent with our findings.', exampleTranslation: '他的结果与我们的发现一致。', difficulty: 3 },
  { id: 'w100', word: 'constitute', phonetic: '/ˈkɒnstɪtjuːt/', partOfSpeech: 'v.', meaning: '构成；组成', example: 'Women constitute half of the population.', exampleTranslation: '女性构成了一半的人口。', difficulty: 3 },
  { id: 'w101', word: 'constraint', phonetic: '/kənˈstreɪnt/', partOfSpeech: 'n.', meaning: '约束；限制', example: 'Budget constraints forced us to change our plans.', exampleTranslation: '预算限制迫使我们改变计划。', difficulty: 3 },
  { id: 'w102', word: 'consult', phonetic: '/kənˈsʌlt/', partOfSpeech: 'v.', meaning: '咨询；查阅', example: 'You should consult a doctor about this.', exampleTranslation: '你应该就此咨询医生。', difficulty: 3 },
  { id: 'w103', word: 'consume', phonetic: '/kənˈsjuːm/', partOfSpeech: 'v.', meaning: '消耗；消费', example: 'The car consumes a lot of fuel.', exampleTranslation: '这辆车消耗很多燃料。', difficulty: 3 },
  { id: 'w104', word: 'contemporary', phonetic: '/kənˈtemprəri/', partOfSpeech: 'adj.', meaning: '当代的；同时代的', example: 'She enjoys contemporary art exhibitions.', exampleTranslation: '她喜欢当代艺术展览。', difficulty: 3 },
  { id: 'w105', word: 'context', phonetic: '/ˈkɒntekst/', partOfSpeech: 'n.', meaning: '上下文；背景', example: 'You must understand the context of the sentence.', exampleTranslation: '你必须理解句子的上下文。', difficulty: 3 },
  { id: 'w106', word: 'contract', phonetic: '/ˈkɒntrækt/', partOfSpeech: 'n./v.', meaning: '合同；收缩', example: 'They signed a contract for the project.', exampleTranslation: '他们为这个项目签了合同。', difficulty: 3 },
  { id: 'w107', word: 'contradict', phonetic: '/ˌkɒntrəˈdɪkt/', partOfSpeech: 'v.', meaning: '反驳；矛盾', example: 'His actions contradict his words.', exampleTranslation: '他的行为与他的话矛盾。', difficulty: 3 },
  { id: 'w108', word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', partOfSpeech: 'v.', meaning: '贡献；投稿', example: 'Everyone should contribute to the community.', exampleTranslation: '每个人都应该为社区做贡献。', difficulty: 3 },
  { id: 'w109', word: 'controversy', phonetic: '/ˈkɒntrəvɜːsi/', partOfSpeech: 'n.', meaning: '争论；争议', example: 'The decision caused much controversy.', exampleTranslation: '这个决定引起了很多争议。', difficulty: 3 },
  { id: 'w110', word: 'convenient', phonetic: '/kənˈviːniənt/', partOfSpeech: 'adj.', meaning: '方便的；便利的', example: 'The hotel is convenient for the airport.', exampleTranslation: '这家酒店靠近机场很方便。', difficulty: 3 },
  { id: 'w111', word: 'convention', phonetic: '/kənˈvenʃən/', partOfSpeech: 'n.', meaning: '惯例；大会', example: 'It is a convention to shake hands when meeting.', exampleTranslation: '见面握手是一种惯例。', difficulty: 3 },
  { id: 'w112', word: 'convert', phonetic: '/kənˈvɜːrt/', partOfSpeech: 'v.', meaning: '转变；改变', example: 'We converted the garage into a bedroom.', exampleTranslation: '我们把车库改造成了卧室。', difficulty: 3 },
  { id: 'w113', word: 'convince', phonetic: '/kənˈvɪns/', partOfSpeech: 'v.', meaning: '使信服；说服', example: 'She convinced him to change his mind.', exampleTranslation: '她说服他改变了想法。', difficulty: 3 },
  { id: 'w114', word: 'cooperate', phonetic: '/kəʊˈɒpəreɪt/', partOfSpeech: 'v.', meaning: '合作；协作', example: 'The two companies agreed to cooperate.', exampleTranslation: '两家公司同意合作。', difficulty: 3 },
  { id: 'w115', word: 'coordinate', phonetic: '/kəʊˈɔːrdɪneɪt/', partOfSpeech: 'v.', meaning: '协调；配合', example: 'We need to coordinate our efforts.', exampleTranslation: '我们需要协调我们的努力。', difficulty: 3 },
  { id: 'w116', word: 'cope', phonetic: '/kəʊp/', partOfSpeech: 'v.', meaning: '应付；处理', example: 'She learned to cope with stress effectively.', exampleTranslation: '她学会了有效应对压力。', difficulty: 3 },
  { id: 'w117', word: 'correspond', phonetic: '/ˌkɒrɪˈspɒnd/', partOfSpeech: 'v.', meaning: '通信；符合', example: 'His account does not correspond with the facts.', exampleTranslation: '他的叙述与事实不符。', difficulty: 3 },
  { id: 'w118', word: 'criterion', phonetic: '/kraɪˈtɪəriən/', partOfSpeech: 'n.', meaning: '标准；准则', example: 'What is the criterion for success?', exampleTranslation: '成功的标准是什么？', difficulty: 3 },
  { id: 'w119', word: 'crucial', phonetic: '/ˈkruːʃəl/', partOfSpeech: 'adj.', meaning: '关键的；至关重要的', example: 'This decision is crucial to our future.', exampleTranslation: '这个决定对我们的未来至关重要。', difficulty: 3 },
  { id: 'w120', word: 'cultivate', phonetic: '/ˈkʌltɪveɪt/', partOfSpeech: 'v.', meaning: '培养；耕种', example: 'We should cultivate good reading habits.', exampleTranslation: '我们应该培养良好的阅读习惯。', difficulty: 3 },

  // === 难度 4：高级词汇 ===
  { id: 'w121', word: 'curriculum', phonetic: '/kəˈrɪkjələm/', partOfSpeech: 'n.', meaning: '课程；课程体系', example: 'The school updated its curriculum this year.', exampleTranslation: '学校今年更新了课程体系。', difficulty: 4 },
  { id: 'w122', word: 'deceive', phonetic: '/dɪˈsiːv/', partOfSpeech: 'v.', meaning: '欺骗；蒙蔽', example: 'Appearances can deceive you easily.', exampleTranslation: '外表很容易欺骗你。', difficulty: 4 },
  { id: 'w123', word: 'decline', phonetic: '/dɪˈklaɪn/', partOfSpeech: 'v./n.', meaning: '下降；拒绝', example: 'Sales have declined by 20% this year.', exampleTranslation: '今年销售额下降了20%。', difficulty: 4 },
  { id: 'w124', word: 'dedicate', phonetic: '/ˈdedɪkeɪt/', partOfSpeech: 'v.', meaning: '致力于；奉献', example: 'She dedicated her life to teaching.', exampleTranslation: '她一生致力于教学。', difficulty: 4 },
  { id: 'w125', word: 'deficiency', phonetic: '/dɪˈfɪʃənsi/', partOfSpeech: 'n.', meaning: '缺乏；不足', example: 'Vitamin deficiency can cause health problems.', exampleTranslation: '维生素缺乏会导致健康问题。', difficulty: 4 },
  { id: 'w126', word: 'delegate', phonetic: '/ˈdelɪɡeɪt/', partOfSpeech: 'v./n.', meaning: '委派；代表', example: 'You should learn to delegate tasks.', exampleTranslation: '你应该学会委派任务。', difficulty: 4 },
  { id: 'w127', word: 'deliberate', phonetic: '/dɪˈlɪbərət/', partOfSpeech: 'adj.', meaning: '故意的；深思熟虑的', example: 'It was a deliberate attempt to mislead us.', exampleTranslation: '这是故意试图误导我们。', difficulty: 4 },
  { id: 'w128', word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', partOfSpeech: 'v.', meaning: '演示；证明', example: 'The experiment demonstrates the theory.', exampleTranslation: '实验证明了这个理论。', difficulty: 4 },
  { id: 'w129', word: 'depict', phonetic: '/dɪˈpɪkt/', partOfSpeech: 'v.', meaning: '描绘；描述', example: 'The painting depicts a beautiful landscape.', exampleTranslation: '这幅画描绘了一幅美丽的风景。', difficulty: 4 },
  { id: 'w130', word: 'deprive', phonetic: '/dɪˈpraɪv/', partOfSpeech: 'v.', meaning: '剥夺；使丧失', example: 'The war deprived them of their homes.', exampleTranslation: '战争剥夺了他们的家园。', difficulty: 4 },
  { id: 'w131', word: 'derive', phonetic: '/dɪˈraɪv/', partOfSpeech: 'v.', meaning: '源于；获得', example: 'Many English words derive from Latin.', exampleTranslation: '很多英语单词源于拉丁语。', difficulty: 4 },
  { id: 'w132', word: 'designate', phonetic: '/ˈdezɪɡneɪt/', partOfSpeech: 'v.', meaning: '指定；标明', example: 'This area is designated as a nature reserve.', exampleTranslation: '这个区域被指定为自然保护区。', difficulty: 4 },
  { id: 'w133', word: 'desperate', phonetic: '/ˈdespərət/', partOfSpeech: 'adj.', meaning: '绝望的；拼命的', example: 'He made a desperate attempt to escape.', exampleTranslation: '他拼命试图逃跑。', difficulty: 4 },
  { id: 'w134', word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', partOfSpeech: 'v.', meaning: '恶化；退化', example: 'His health began to deteriorate rapidly.', exampleTranslation: '他的健康状况开始迅速恶化。', difficulty: 4 },
  { id: 'w135', word: 'devise', phonetic: '/dɪˈvaɪz/', partOfSpeech: 'v.', meaning: '设计；策划', example: 'They devised a plan to solve the problem.', exampleTranslation: '他们设计了一个解决问题的方案。', difficulty: 4 },
  { id: 'w136', word: 'diagnose', phonetic: '/ˈdaɪəɡnəʊz/', partOfSpeech: 'v.', meaning: '诊断；判断', example: 'The doctor diagnosed him with diabetes.', exampleTranslation: '医生诊断他患有糖尿病。', difficulty: 4 },
  { id: 'w137', word: 'dilemma', phonetic: '/dɪˈlemə/', partOfSpeech: 'n.', meaning: '困境；两难', example: 'She faced a dilemma between career and family.', exampleTranslation: '她面临事业和家庭之间的两难。', difficulty: 4 },
  { id: 'w138', word: 'dimension', phonetic: '/daɪˈmenʃən/', partOfSpeech: 'n.', meaning: '维度；尺寸', example: 'The problem has many different dimensions.', exampleTranslation: '这个问题有很多不同的维度。', difficulty: 4 },
  { id: 'w139', word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', partOfSpeech: 'v.', meaning: '减少；削弱', example: 'The pain gradually diminished over time.', exampleTranslation: '疼痛随着时间逐渐减轻。', difficulty: 4 },
  { id: 'w140', word: 'discipline', phonetic: '/ˈdɪsəplɪn/', partOfSpeech: 'n./v.', meaning: '纪律；学科', example: 'Success requires discipline and hard work.', exampleTranslation: '成功需要纪律和努力。', difficulty: 4 },
  { id: 'w141', word: 'disclose', phonetic: '/dɪsˈkləʊz/', partOfSpeech: 'v.', meaning: '揭露；公开', example: 'The company refused to disclose the information.', exampleTranslation: '公司拒绝公开这些信息。', difficulty: 4 },
  { id: 'w142', word: 'discourse', phonetic: '/ˈdɪskɔːrs/', partOfSpeech: 'n.', meaning: '话语；论述', example: 'Academic discourse requires clear logic.', exampleTranslation: '学术论述需要清晰的逻辑。', difficulty: 4 },
  { id: 'w143', word: 'discriminate', phonetic: '/dɪˈskrɪmɪneɪt/', partOfSpeech: 'v.', meaning: '歧视；区别', example: 'It is wrong to discriminate against anyone.', exampleTranslation: '歧视任何人都是不对的。', difficulty: 4 },
  { id: 'w144', word: 'dismiss', phonetic: '/dɪsˈmɪs/', partOfSpeech: 'v.', meaning: '解雇；驳回', example: 'The judge dismissed the case due to lack of evidence.', exampleTranslation: '法官因证据不足驳回了案件。', difficulty: 4 },
  { id: 'w145', word: 'displace', phonetic: '/dɪsˈpleɪs/', partOfSpeech: 'v.', meaning: '取代；置换', example: 'Machines have displaced many workers.', exampleTranslation: '机器取代了许多工人。', difficulty: 4 },
  { id: 'w146', word: 'dispose', phonetic: '/dɪˈspəʊz/', partOfSpeech: 'v.', meaning: '处理；处置', example: 'You must dispose of waste properly.', exampleTranslation: '你必须正确处理废物。', difficulty: 4 },
  { id: 'w147', word: 'dispute', phonetic: '/dɪˈspjuːt/', partOfSpeech: 'n./v.', meaning: '争论；纠纷', example: 'The neighbors had a dispute over the fence.', exampleTranslation: '邻居们因围栏发生了纠纷。', difficulty: 4 },
  { id: 'w148', word: 'dissolve', phonetic: '/dɪˈzɒlv/', partOfSpeech: 'v.', meaning: '溶解；解散', example: 'Sugar dissolves quickly in hot water.', exampleTranslation: '糖在热水中很快溶解。', difficulty: 4 },
  { id: 'w149', word: 'distinct', phonetic: '/dɪˈstɪŋkt/', partOfSpeech: 'adj.', meaning: '不同的；明显的', example: 'The two species are quite distinct.', exampleTranslation: '这两个物种非常不同。', difficulty: 4 },
  { id: 'w150', word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/', partOfSpeech: 'v.', meaning: '区分；辨别', example: 'Can you distinguish between the two sounds?', exampleTranslation: '你能区分这两种声音吗？', difficulty: 4 },
  { id: 'w151', word: 'distribute', phonetic: '/dɪˈstrɪbjuːt/', partOfSpeech: 'v.', meaning: '分配；分发', example: 'The company distributes goods worldwide.', exampleTranslation: '该公司在全球分销商品。', difficulty: 4 },
  { id: 'w152', word: 'diverse', phonetic: '/daɪˈvɜːrs/', partOfSpeech: 'adj.', meaning: '多样的；不同的', example: 'The city has a diverse population.', exampleTranslation: '这座城市有多样化的人口。', difficulty: 4 },
  { id: 'w153', word: 'domestic', phonetic: '/dəˈmestɪk/', partOfSpeech: 'adj.', meaning: '国内的；家庭的', example: 'Domestic flights are cheaper than international ones.', exampleTranslation: '国内航班比国际航班便宜。', difficulty: 4 },
  { id: 'w154', word: 'dominant', phonetic: '/ˈdɒmɪnənt/', partOfSpeech: 'adj.', meaning: '主导的；占优势的', example: 'English is the dominant language in business.', exampleTranslation: '英语是商业中的主导语言。', difficulty: 4 },
  { id: 'w155', word: 'dramatic', phonetic: '/drəˈmætɪk/', partOfSpeech: 'adj.', meaning: '戏剧性的；引人注目的', example: 'There has been a dramatic improvement.', exampleTranslation: '已经有了显著的改善。', difficulty: 4 },
  { id: 'w156', word: 'duration', phonetic: '/djuˈreɪʃən/', partOfSpeech: 'n.', meaning: '持续时间；期间', example: 'The duration of the exam is two hours.', exampleTranslation: '考试时间为两小时。', difficulty: 4 },
  { id: 'w157', word: 'dynamic', phonetic: '/daɪˈnæmɪk/', partOfSpeech: 'adj.', meaning: '动态的；充满活力的', example: 'The city has a dynamic economy.', exampleTranslation: '这座城市有充满活力的经济。', difficulty: 4 },
  { id: 'w158', word: 'elaborate', phonetic: '/ɪˈlæbərət/', partOfSpeech: 'adj./v.', meaning: '精心制作的；详细阐述', example: 'Could you elaborate on your proposal?', exampleTranslation: '你能详细阐述你的提案吗？', difficulty: 4 },
  { id: 'w159', word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', partOfSpeech: 'v.', meaning: '消除；淘汰', example: 'We must eliminate all errors from the report.', exampleTranslation: '我们必须消除报告中的所有错误。', difficulty: 4 },
  { id: 'w160', word: 'embrace', phonetic: '/ɪmˈbreɪs/', partOfSpeech: 'v.', meaning: '拥抱；欣然接受', example: 'We should embrace new technology.', exampleTranslation: '我们应该欣然接受新技术。', difficulty: 4 },

  // === 难度 5：高频考试词汇 ===
  { id: 'w161', word: 'emerge', phonetic: '/ɪˈmɜːrdʒ/', partOfSpeech: 'v.', meaning: '出现；浮现', example: 'New evidence has emerged in the case.', exampleTranslation: '该案件出现了新证据。', difficulty: 5 },
  { id: 'w162', word: 'emission', phonetic: '/ɪˈmɪʃən/', partOfSpeech: 'n.', meaning: '排放；散发', example: 'The country aims to reduce carbon emissions.', exampleTranslation: '该国旨在减少碳排放。', difficulty: 5 },
  { id: 'w163', word: 'emphasis', phonetic: '/ˈemfəsɪs/', partOfSpeech: 'n.', meaning: '强调；重点', example: 'The emphasis is on quality rather than quantity.', exampleTranslation: '重点是质量而非数量。', difficulty: 5 },
  { id: 'w164', word: 'empirical', phonetic: '/ɪmˈpɪrɪkəl/', partOfSpeech: 'adj.', meaning: '经验主义的；实证的', example: 'The theory is based on empirical evidence.', exampleTranslation: '这个理论基于实证证据。', difficulty: 5 },
  { id: 'w165', word: 'encounter', phonetic: '/ɪnˈkaʊntər/', partOfSpeech: 'v./n.', meaning: '遭遇；邂逅', example: 'We encountered many difficulties along the way.', exampleTranslation: '我们一路上遇到了很多困难。', difficulty: 5 },
  { id: 'w166', word: 'endeavor', phonetic: '/ɪnˈdevər/', partOfSpeech: 'n./v.', meaning: '努力；尝试', example: 'We should endeavor to improve our skills.', exampleTranslation: '我们应该努力提高技能。', difficulty: 5 },
  { id: 'w167', word: 'endure', phonetic: '/ɪnˈdjʊər/', partOfSpeech: 'v.', meaning: '忍受；持久', example: 'She endured years of hardship.', exampleTranslation: '她忍受了多年的艰辛。', difficulty: 5 },
  { id: 'w168', word: 'enforce', phonetic: '/ɪnˈfɔːrs/', partOfSpeech: 'v.', meaning: '执行；强制', example: 'The police enforce the law strictly.', exampleTranslation: '警方严格执法。', difficulty: 5 },
  { id: 'w169', word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', partOfSpeech: 'v.', meaning: '参与；吸引', example: 'Students should engage in class discussions.', exampleTranslation: '学生应该参与课堂讨论。', difficulty: 5 },
  { id: 'w170', word: 'enhance', phonetic: '/ɪnˈhɑːns/', partOfSpeech: 'v.', meaning: '增强；提高', example: 'This software enhances photo quality.', exampleTranslation: '这款软件提高了照片质量。', difficulty: 5 },
  { id: 'w171', word: 'enormous', phonetic: '/ɪˈnɔːrməs/', partOfSpeech: 'adj.', meaning: '巨大的；庞大的', example: 'The project requires an enormous amount of time.', exampleTranslation: '这个项目需要大量的时间。', difficulty: 5 },
  { id: 'w172', word: 'enterprise', phonetic: '/ˈentərpraɪz/', partOfSpeech: 'n.', meaning: '企业；事业', example: 'He started a small enterprise in his hometown.', exampleTranslation: '他在家乡创办了一家小企业。', difficulty: 5 },
  { id: 'w173', word: 'enthusiasm', phonetic: '/ɪnˈθjuːziæzəm/', partOfSpeech: 'n.', meaning: '热情；热忱', example: 'She showed great enthusiasm for the project.', exampleTranslation: '她对这个项目表现出极大的热情。', difficulty: 5 },
  { id: 'w174', word: 'equivalent', phonetic: '/ɪˈkwɪvələnt/', partOfSpeech: 'adj./n.', meaning: '等同的；等价物', example: 'One mile is equivalent to 1.6 kilometers.', exampleTranslation: '一英里等于1.6公里。', difficulty: 5 },
  { id: 'w175', word: 'erode', phonetic: '/ɪˈrəʊd/', partOfSpeech: 'v.', meaning: '侵蚀；逐渐削弱', example: 'Wind and rain erode the soil over time.', exampleTranslation: '风雨随着时间侵蚀土壤。', difficulty: 5 },
  { id: 'w176', word: 'essential', phonetic: '/ɪˈsenʃəl/', partOfSpeech: 'adj.', meaning: '必要的；本质的', example: 'Water is essential for life.', exampleTranslation: '水对生命是必不可少的。', difficulty: 5 },
  { id: 'w177', word: 'establish', phonetic: '/ɪˈstæblɪʃ/', partOfSpeech: 'v.', meaning: '建立；确立', example: 'The company was established in 1990.', exampleTranslation: '该公司成立于1990年。', difficulty: 5 },
  { id: 'w178', word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', partOfSpeech: 'v.', meaning: '评估；评价', example: 'We need to evaluate the results carefully.', exampleTranslation: '我们需要仔细评估结果。', difficulty: 5 },
  { id: 'w179', word: 'evidence', phonetic: '/ˈevɪdəns/', partOfSpeech: 'n.', meaning: '证据；证明', example: 'There is strong evidence to support the theory.', exampleTranslation: '有强有力的证据支持这个理论。', difficulty: 5 },
  { id: 'w180', word: 'evolve', phonetic: '/ɪˈvɒlv/', partOfSpeech: 'v.', meaning: '进化；发展', example: 'Technology continues to evolve rapidly.', exampleTranslation: '技术继续快速发展。', difficulty: 5 },
  { id: 'w181', word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', partOfSpeech: 'v.', meaning: '夸大；夸张', example: 'He tends to exaggerate his achievements.', exampleTranslation: '他倾向于夸大自己的成就。', difficulty: 5 },
  { id: 'w182', word: 'exceed', phonetic: '/ɪkˈsiːd/', partOfSpeech: 'v.', meaning: '超过；超出', example: 'The results exceeded our expectations.', exampleTranslation: '结果超出了我们的预期。', difficulty: 5 },
  { id: 'w183', word: 'exception', phonetic: '/ɪkˈsepʃən/', partOfSpeech: 'n.', meaning: '例外；除外', example: 'Everyone passed the test without exception.', exampleTranslation: '所有人都毫无例外地通过了考试。', difficulty: 5 },
  { id: 'w184', word: 'excessive', phonetic: '/ɪkˈsesɪv/', partOfSpeech: 'adj.', meaning: '过度的；过多的', example: 'Excessive use of phones is harmful to health.', exampleTranslation: '过度使用手机有害健康。', difficulty: 5 },
  { id: 'w185', word: 'exclude', phonetic: '/ɪkˈskluːd/', partOfSpeech: 'v.', meaning: '排除；排斥', example: 'The price excludes tax and delivery fees.', exampleTranslation: '价格不包括税和运费。', difficulty: 5 },
  { id: 'w186', word: 'execute', phonetic: '/ˈeksɪkjuːt/', partOfSpeech: 'v.', meaning: '执行；实施', example: 'They executed the plan perfectly.', exampleTranslation: '他们完美地执行了计划。', difficulty: 5 },
  { id: 'w187', word: 'exhibit', phonetic: '/ɪɡˈzɪbɪt/', partOfSpeech: 'v./n.', meaning: '展示；展览品', example: 'The museum exhibits artifacts from ancient times.', exampleTranslation: '博物馆展出古代文物。', difficulty: 5 },
  { id: 'w188', word: 'expand', phonetic: '/ɪkˈspænd/', partOfSpeech: 'v.', meaning: '扩大；膨胀', example: 'The company plans to expand overseas.', exampleTranslation: '公司计划向海外扩张。', difficulty: 5 },
  { id: 'w189', word: 'explicit', phonetic: '/ɪkˈsplɪsɪt/', partOfSpeech: 'adj.', meaning: '明确的；清楚的', example: 'The instructions were quite explicit.', exampleTranslation: '说明非常明确。', difficulty: 5 },
  { id: 'w190', word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', partOfSpeech: 'v.', meaning: '利用；开发', example: 'We should exploit renewable energy sources.', exampleTranslation: '我们应该开发可再生能源。', difficulty: 5 },
  { id: 'w191', word: 'expose', phonetic: '/ɪkˈspəʊz/', partOfSpeech: 'v.', meaning: '揭露；暴露', example: 'The journalist exposed the corruption scandal.', exampleTranslation: '记者揭露了腐败丑闻。', difficulty: 5 },
  { id: 'w192', word: 'extend', phonetic: '/ɪkˈstend/', partOfSpeech: 'v.', meaning: '延伸；扩展', example: 'The deadline has been extended by one week.', exampleTranslation: '截止日期延长了一周。', difficulty: 5 },
  { id: 'w193', word: 'extensive', phonetic: '/ɪkˈstensɪv/', partOfSpeech: 'adj.', meaning: '广泛的；大量的', example: 'She has extensive experience in marketing.', exampleTranslation: '她在市场营销方面有丰富的经验。', difficulty: 5 },
  { id: 'w194', word: 'extract', phonetic: '/ɪkˈstrækt/', partOfSpeech: 'v./n.', meaning: '提取；摘录', example: 'Scientists extracted DNA from the samples.', exampleTranslation: '科学家从样本中提取了DNA。', difficulty: 5 },
  { id: 'w195', word: 'facilitate', phonetic: '/fəˈsɪlɪteɪt/', partOfSpeech: 'v.', meaning: '促进；使便利', example: 'Technology can facilitate communication.', exampleTranslation: '技术可以促进沟通。', difficulty: 5 },
  { id: 'w196', word: 'feasible', phonetic: '/ˈfiːzəbl/', partOfSpeech: 'adj.', meaning: '可行的；可能的', example: 'Is the plan financially feasible?', exampleTranslation: '这个计划在经济上可行吗？', difficulty: 5 },
  { id: 'w197', word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', partOfSpeech: 'v.', meaning: '波动；起伏', example: 'Oil prices fluctuate from day to day.', exampleTranslation: '油价每天都在波动。', difficulty: 5 },
  { id: 'w198', word: 'formulate', phonetic: '/ˈfɔːrmjuleɪt/', partOfSpeech: 'v.', meaning: '制定；阐述', example: 'We need to formulate a new strategy.', exampleTranslation: '我们需要制定新策略。', difficulty: 5 },
  { id: 'w199', word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', partOfSpeech: 'adj.', meaning: '基本的；根本的', example: 'Freedom of speech is a fundamental right.', exampleTranslation: '言论自由是一项基本权利。', difficulty: 5 },
  { id: 'w200', word: 'generate', phonetic: '/ˈdʒenəreɪt/', partOfSpeech: 'v.', meaning: '产生；引起', example: 'The project will generate new jobs.', exampleTranslation: '该项目将创造新的就业机会。', difficulty: 5 },
]
